### ISSUE TITLE
An error occurs when running the code

### ISSUE THREAD

**Issue by Guanjinqu** [ysfhtxn/Composite-Hedges-Nanopores#2]
hello
I installed the yaml environment as the readme and tried to run robustness_test.py. on decoding it comes up with not being able to find . /assembly/temp_batch _output.fasta file error. So I'm looking for help from the author.

**Comment by Guanjinqu** [comment]
We reconfirmed that muscle and mmseqs are installed correctly, but we still get the above error. I hope to get help from the author.
<img width="1050" alt="微信图片_20241212224523" src="https://github.com/user-attachments/assets/c9f8625b-ae54-44b9-b835-c32243760d73" />
<img width="1470" alt="微信图片_20241212224533" src="https://github.com/user-attachments/assets/d9bb36f3-b94a-4b3a-8b35-6cb9d0a210a8" />

**Comment by ysfhtxn** [comment]
Hi, thanks for your attention to our work.
I notice that the MUSCLE version you installed is v3.8.1551. Could you reinstall MUSCLE v5.* and rerun the process?
Here is the link [MUSCLE](https://github.com/rcedgar/muscle/releases). Version 5.1 is recommended since other version is not be tested.
Thank you for reminding me to specify MUSCLE version number and it will be updated to README.
